# This is a basic workflow to help you get started with Actions

name: Dunamis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Test compile 
        run: ./duna.out run examples/print.dun
