# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test cli no args response
        run: ./duna.out

      # Runs a set of commands using the runners shell
      - name: Test compile 
        run: ./duna.out compile examples/print.dun
